### PR TITLE
fix(json): added toaster component to the toast component json

### LINKED ISSUE #238: Toaster doesn't ship with the cli tool
`<Toaster />` component doesn't ship with the cli-tool `npx shadcn-ui add toast`

Even the manual installation shows steps for Toasted component.

Although all the components are available to make the toaster..

Suggestion: Make another component file like the `use-toast.ts` containing Toaster

### PR DESCRIPTION
**Pull request by ricci2511**
Should fix #238 and #234.

### CODE REVIEW

**Review by NaralC — COMMENTED** [review]
Nice job! I noticed the same problem haha

**Comment by shadcn** [comment]
@ricci2511 The config file for the CLI is here: https://github.com/shadcn/ui/blob/main/apps/www/config/components.ts

(Note: I'm adding component dependency to the CLI which should fix this issue).

**Comment by 18jad** [comment]
@shadcn  This is needed please merge it, my toast is not working automatically i have to add the component manually.

**Comment by strat-ileris** [comment]
> @shadcn This is needed please merge it, my toast is not working automatically i have to add the component manually for it to work.

@18jad How did you add it manually?

**Review by jocarrd — APPROVED** [review]

**Comment by 18jad** [comment]
> > @shadcn This is needed please merge it, my toast is not working automatically i have to add the component manually for it to work.
> 
> @18jad How did you add it manually?

Sorry for the late reply, but go into the file changed here copy the code content, and create a toaster.tsx in your components folder, and add the code you copied.

**Comment by vincent-vade** [comment]
> > @shadcn This is needed please merge it, my toast is not working automatically i have to add the component manually for it to work.
> 
> @18jad How did you add it manually?

Something like that based on [merge](https://github.com/shadcn/ui/pull/243) 
```
'use client';

import {
  Toast,
  ToastAction,
  ToastClose,
  ToastDescription,
  ToastProvider,
  ToastTitle,
  ToastViewport,
} from '@/components/ui/toast';
import { useToast } from '@/components/ui/use-toast';

export const Toaster = () => {
  const { toasts } = useToast();

  return (
    <ToastProvider>
      {toasts.map(({ id, title, description, action, ...props }) => (
        <Toast key={id} {...props}>
          {title && <ToastTitle>{title}</ToastTitle>}
          {description && <ToastDescription>{description}</ToastDescription>}
          {action && (
            <ToastAction altText="close">
              <ToastClose />
            </ToastAction>
          )}
        </Toast>
      ))}
      <ToastViewport />
    </ToastProvider>
  );
};
```

**Comment by bozd4g** [comment]
Will you merge these above changes to avoid this kinda search that we're doing to fix our project's this problem?

**Comment by shadcn** [comment]
I believe this is fixed now. Marking this as completed. Feel free to reopen if not. Thanks everyone. Appreciate the help on this.

**Pull request closed without merging**
