### PR TITLE
fix(cli): remix detection

### PR DESCRIPTION
**Pull request by Fluf22**
# What

Some remix templates doesn't package a `vite.config.*` file at their root.
It's the case for the recommended starter "stack" templates: blues-stack, indie-stack and grunge-stack.
As recommended in a TODO comment, it's more suitable to check for a `@remix-run/*` dependency in the package dependencies.

# How

- decouple vite and remix checks
- retrieve the `package.json`
- allow passing a `cwd` to the retrieval method
- remove the "empty config file list" that can be empty for a remix stack
- check that the `package.json` contains a `@remix-run/*` dependency

# Test

Added a fixture by running `npx create-remix@latest --template remix-run/indie-stack` in the [frameworks](/Fluf22/shadcn-ui/tree/fix/cli-remix-detection/packages/cli/test/fixtures/frameworks) folder and named it `remix-indie-stack`, if ever we want another stack as a fixture later

---

Fixes shadcn-ui/ui#4967

### CODE REVIEW

**Comment by shadcn** [comment]
@Fluf22 Ah. This is helpful. I'll review. It looks like some styling changes got in the PR. is this intended?

**Comment by Fluf22** [comment]
Hmm no, sorry! I'll revert it
I'm not sure to understand which styling are you talking about?

**Comment by shadcn** [comment]
oh my bad, I did not see that the new lines where inside fixtures. all good. I'll review.

**Comment by Fluf22** [comment]
Indeed, I didn't bother applying any style to the fixture code
I assumed it wasn't necessary ☺️

**Comment by shadcn** [comment]
@Fluf22 I just noticed we made the changes in `cli`. it should be in `packages/shadcn` instead. sorry about this. i'll add a deprecation notice on the cli.

**Comment by Fluf22** [comment]
My bad! I made the mistake: as I couldn't find the thrown error, I also based this branch on the `shadcn/cli-2` one, while it should be based on `main` instead, with the updates in the `packages/shadcn` folder, like you said.

Let me update the PR!

**Comment by Fluf22** [comment]
@shadcn updated! Sorry for the lost time

**Review by shadcn — APPROVED** [review]
All good. Appreciate this fix. Thank you.

**Pull request merged**
