### PR TITLE
docs: update contrubuting.md and next.mdx

### LINKED ISSUE #1116: add one step for installing "next-themes"
It is better to say that the first step is installing the "next-themes" package for this page of documnetation:
https://ui.shadcn.com/docs/dark-mode/next

### PR DESCRIPTION
**Pull request by NikharPandya**
### 1. Added Commit convention to CONTRIBUTING.md 

screencapture-github-NikharPandya-ui-blob-main-CONTRIBUTING-md-2023-08-25-17_30_39

### CODE REVIEW

**Comment by NikharPandya** [comment]
@dan5py Hey dan. Could you review the pr and push it forward?

**Comment by jocarrd** [comment]
nice ✨

**Review by jocarrd — APPROVED** [review]

**Comment by NikharPandya** [comment]
@shadcn Hey, shad, still need one more review, Could you take a look? tagged Dan but looks like he is busy, Thanks.

**Review by dan5py — APPROVED** [review]
👍

**Comment by NikharPandya** [comment]
@dan5py Thanks man.

**Review by shadcn — APPROVED** [review]
Thank you.

**Pull request merged**
