### PR TITLE
feat: dialog position and size features are added

### PR DESCRIPTION
**Pull request by towhidstack**
Hello @shadcn,

I hope you're doing well. I've created this pull request to propose an enhancement to the shadcn-uI library. I've added position and size variants to the Dialog component, which I believe would enhance the versatility and usability of the library.

Changes Made:

Added new position options (left, center, right, top-left, top-center, top-right,  bottom-left, bottom-center, bottom-right) to the Dialog component.
Included size options (small, medium, large, extra-large, super-large, ultra-large, full) to allow for greater flexibility in adapting the dialog to different content needs.

I kindly request you to review this pull request at your earliest convenience. Your feedback and suggestions are highly valued, and I'm open to making any necessary adjustments to ensure the quality and cohesion of the library. 

Issue number is #1367

Best regards,
Towhid Hasan

image
image
image
image
image
image

### CODE REVIEW

**Comment by Josevictor2** [comment]
up

**Comment by jocarrd** [comment]
Great, it's a feature that until now I was using in my projects because it's very useful. Good job

**Review by jocarrd — APPROVED** [review]

**Comment by henrybabbage** [comment]
Really nice work. Was about to build the same variants and then came across this repo. By the way, minor, but `dialogVariants` is mispelt in the commit as `dialogVarients`. Thanks again.

**Comment by TowhidBD** [comment]
> Really nice work. Was about to build the same variants and then came across this pr. By the way, minor, but `dialogVariants` is mispelt in the commit as `dialogVarients`. Thanks again.

Thank you for your feedback! I appreciate your kind words and a keen eye for detail. I've corrected the spelling mistake, and the updated commit now reads "dialogVariants" instead of "dialogVarients." Thanks again for your support!

**Comment by shadcn** [comment]
@towhidstack This looks great. However we're trying to keep the props minimal for the components and let you customize per project. I think this makes a great example though. Can we cover this in documentation instead?

**Comment by towhidstack** [comment]
> @towhidstack This looks great. However we're trying to keep the props minimal for the components and let you customize per project. I think this makes a great example though. Can we cover this in documentation instead?

sure

**Comment by javed24** [comment]
neat work @towhidstack! 💯 

I noticed for `DialogContent`, we're passing `className` to `cn` _outside_ of the `dialogVariants` like so -

```
className={cn(dialogVariants({ position, size }), className)}
```

which makes sense to me. I did notice, however, that for buttons, shadcn destructures/passes `className` from within `buttonVariants` -

```
className={cn(buttonVariants({ variant, size, className }))}
```

I wonder whether that makes any difference.

**Comment by mauriciocrecencio** [comment]
I was looking for a way to change Width of Dialog, but here size and position props apparently not working 

CleanShot 2024-03-07 at 21 42 43
CleanShot 2024-03-07 at 21 43 12

**Comment by towhidstack** [comment]
> I was looking for a way to change Width of Dialog, but here size and position props apparently not working
> 
> CleanShot 2024-03-07 at 21 42 43 CleanShot 2024-03-07 at 21 43 12

Since this pull request hasn't been merged, you're unable to proceed with that action. you can change the dialog width/height using tailwind CSS class.

**Comment by mauriciocrecencio** [comment]
> > I was looking for a way to change Width of Dialog, but here size and position props apparently not working
> > CleanShot 2024-03-07 at 21 42 43 CleanShot 2024-03-07 at 21 43 12
> 
> Since this pull request hasn't been merged, you're unable to proceed with that action. you can change the dialog width/height using tailwind CSS class.

Oh, I didn't see the comment from shadcn 😬 
Setting a custom width for Dialog component only works when I removed max-w-lg in components/ui/dialog.tsx

**Comment by erikdemarco** [comment]
> > @towhidstack This looks great. However we're trying to keep the props minimal for the components and let you customize per project. I think this makes a great example though. Can we cover this in documentation instead?
> 
> sure

why i didnt see position and size mentioned in official documentation here:

https://ui.shadcn.com/docs/components/dialog

Do i miss something?

**Pull request closed without merging**
