### PR TITLE
Refactor(icon.tsx) twitter icon update to latest version X icon

### PR DESCRIPTION
**Pull request by captain-Akshay**
just fixed the twitter icon svg to the X twitter icon svg and size was bigger so decreased it a bit

### CODE REVIEW

**Comment by captain-Akshay** [comment]
##BEFORE
image


##AFTER
image
@shadcn

**Comment by captain-Akshay** [comment]
##next template icon changed 
image

**Comment by captain-Akshay** [comment]
@shadcn Sorry for the inconvenience fixed it thanks for pointing it out!!

**Comment by captain-Akshay** [comment]
@shadcn sorry to ping you again but any issue with this one?

**Review by shadcn — APPROVED** [review]
Still think the bird looks better but love the PR :) Thank you.

**Pull request merged**
