### PR TITLE
Modularize lucide-react imports

### LINKED ISSUE #267: Improve development speed - modularise lucide imports
For those who ran into the same problem as myself, consider speeding up development speeds by modularising the lucide imports via the next config:

```ts
// next.config.js
//...
modularizeImports: {
    "lucide-react": {
      transform: "lucide-react/dist/esm/icons/{{kebabCase member}}",
    },
  },
//...
```

### PR DESCRIPTION
**Pull request by ap-1**
Closes #267

### CODE REVIEW

**Review by shadcn — APPROVED** [review]
This is handy. Thank you.

**Comment by shadcn** [comment]
@ap-1 This is failing with the following error:

```
./app/examples/forms/account/account-form.tsx
Module not found: Can't resolve 'lucide-react/dist/esm/icons/calendar-icon'
```

**Comment by ap-1** [comment]
> ```
> ./app/examples/forms/account/account-form.tsx
> Module not found: Can't resolve 'lucide-react/dist/esm/icons/calendar-icon'
> ```

The issue seems to occur when an alias for the icon is used instead of the original file. For example:

```js
/* apps/www/components/mobile-nav.tsx */

import { SidebarOpen } from "lucide-react" // errors
import { PanelLeftOpen as SidebarOpen } from "lucide-react" // works fine
```

```ts
/* node_modules/lucide-react/dist/lucide-react.d.ts */

// PanelLeftOpen aliases
export declare const PanelLeftOpenIcon: LucideIcon;
export declare const LucidePanelLeftOpen: LucideIcon;
export declare const SidebarOpen: LucideIcon;
```

I'm not quite sure how to work around this in `modularizeImports`, so here's what we could do:
1. Hold off on this until we figure out how to make `modularizeImports` work with aliases
2. Create an eslint rule that enforces the use of the original `lucide-react` icon names instead of their aliases
    - I'm not sure if this is a good idea. It sounds pretty instrusive.

**Comment by shadcn** [comment]
@ap-1 Thanks for the fix. This is now supported out of the box in Next.js. See https://github.com/vercel/next.js/pull/53051

(Closing this as completed. Feel free to reopen if not).

**Pull request closed without merging**
