### PR TITLE
feat: disable animations for users who requested reduced motion

### PR DESCRIPTION
**Pull request by emicba**
Let's honour user motion preference!

### CODE REVIEW

**Comment by emicba** [comment]
Maybe we could also hide the spinner in the example loading button
```diff
 export function ButtonLoading() {
   return (
     <Button disabled>
-      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
+      <Loader2 className="mr-2 h-4 w-4 animate-spin motion-reduce:hidden" />
       Please wait
     </Button>
   )
```

And we can update the apple music example as well
wdyt @shadcn?

**Comment by shadcn** [comment]
This looks good. Useful addition. I'll review. Thank you.

**Comment by shadcn** [comment]
ok I still want to add this. Adding it to the roadmap so that I can get back to it.

**Comment by emicba** [comment]
I believe we can prefix all classed related with transition to `motion-safe` or add something like this in the globals.css
```css
@layer base {
  * {
    @apply motion-reduce:duration-0;
  }
}
```

**Comment by shadcn** [comment]
Anyone up for fixing the merge conflicts? 👀

**Pull request closed without merging**
