### PR TITLE
fix: Update carousel deprecated imported types #2376

### LINKED ISSUE #2376: Carousel imported types are no longer available on module "embla-carousel-react"
Types **EmblaCarouselType**, **EmblaOptionsType** and **EmblaPluginType** are no longer available on module `embla-carousel-react`. The types have been migrated to `embla-carousel`

### Expected behaviour
Screenshot (6)

### Current behaviour
Screenshot (5)

### PR DESCRIPTION
**Pull request by franfares10**
The library embla-carousel has changed the location of this types to the core package (embla-carousel).

**Actions needed:** pnpm install embla-carousel

Fixes #2376

### CODE REVIEW

**Comment by arvind-iyer-2001** [comment]
This actually does work
Please merge

**Comment by dan5py** [comment]
Hi @franfares10, you need to update both themes (`default` and `new-york`) and build the registry. 
Take a look at the [`CONTRIBUTING.md`](https://github.com/shadcn-ui/ui/blob/main/CONTRIBUTING.md) file 🎉.

**Comment by franfares10** [comment]
Done @dan5py ! Thanks for the comments 😅

**Review by dan5py — APPROVED** [review]
👍

**Comment by dan5py** [comment]
Hi again @franfares10, I noticed that there's another PR related to this issue (#2326), I think that the solution offered by @Gomah is slightly better since it doesn't require addition dependecies.

Didn't notice it at first, sorry.

**Pull request closed without merging**
