### PR TITLE
refactor(components): remove redundant empty interfaces from Input, Command, and Textarea components

### PR DESCRIPTION
**Pull request by Jacksonmills**
Simplified props handling by removing redundant empty interfaces (`InputProps`, `CommandDialogProps`, `TextareaProps`). Each component now directly extends native HTML/lib attributes (`React.InputHTMLAttributes`, `DialogProps`, etc.), improving code clarity and maintainability.

image

The main motivation behind this change is to address the `@typescript-eslint/no-empty-object-type` rule violation, as seen in the screenshot provided. This rule flags empty interfaces that are equivalent to their supertypes, resulting in type errors during build time. By eliminating these redundant interfaces, the components comply with ESLint rules, prevent type errors, and ensure a smoother build process.

Alternatively, we could keep prop types separate by using type instead of interface if we want to extend or add custom props in the future, avoiding linting issues related to empty interfaces.

Key changes:
- Updated `Command`, `Input`, and `Textarea` components to directly use native HTML/lib attribute types.
- Removed redundant interfaces, reducing unnecessary complexity in the codebase.
- Improved maintainability and streamlined props management for future modifications.

This refactor enhances the overall quality of the code and prevents similar ESLint issues from occurring, ensuring consistent type safety without altering any functionality.

### CODE REVIEW

**Comment by Jacksonmills** [comment]
@shadcn am I missing something in the contribution guide? I am not seeing the updates to the components in docs after `pnpm build:registry`

**Comment by Jacksonmills** [comment]
fixes in part https://github.com/shadcn-ui/ui/issues/5214

**Comment by Jacksonmills** [comment]
@shadcn This one's had a couple of duplicate PRs. Any thoughts on merging? Let me know if you need any adjustments, like converting to types instead of interfaces as an alternative solution.

Thanks!

**Review by shadcn — CHANGES_REQUESTED** [review]
@Jacksonmills Thanks for working on this fix. Looks good.

Could we move to `React.ComponentProps` instead of `React.InputHTMLAttributes` please? This is what I've been using moving forward.

eg. `React.ComponentProps<"input">` instead of `React.InputHTMLAttributes<HTMLInputElement>`

**Comment by Jacksonmills** [comment]
> @Jacksonmills Thanks for working on this fix. Looks good.
> 
> Could we move to `React.ComponentProps` instead of `React.InputHTMLAttributes` please? This is what I've been using moving forward.
> 
> eg. `React.ComponentProps<"input">` instead of `React.InputHTMLAttributes<HTMLInputElement>`

Thanks for the review! Should be all good now 🫡

**Review by shadcn — APPROVED** [review]
Awesome. Thanks @Jacksonmills

**Pull request merged**
