### PR TITLE
feat(www): add bun support for installation commands

### PR DESCRIPTION
**Pull request by rgodha24**
The title basically says it all

adding a component:
copying a command with npm, yarn, pnpm, bun as options

creating an app:
create-next-app with npm, yarn, pnpm, bun

initing shadcn-ui:
shadcn-ui init with npm, yarn, pnpm, bun

### CODE REVIEW

**Comment by ParthJadhav** [comment]
I can back this change ! Worth adding 🤝

**Comment by rafaelsilva81** [comment]
Oh, I started doing [this](https://github.com/rafaelsilva81/ui/commit/28f0223ddbbf359e0ad2fa7ffe0e4c11edfbb1b3) because I saw #1480 but great to see someone already did it

This is a good change!

**Comment by rgodha24** [comment]
It's honestly probably my bad - I forgot to make an issue before the pr. It would be great if we can get this merged though :)

**Comment by jocarrd** [comment]
I love bun and I believe it's good to provide support in the documentation

**Review by jocarrd — APPROVED** [review]

**Comment by rgodha24** [comment]
@shadcn can you review this pr whenever you get the chance? It's tiny pr and it would be great to get merged.

**Review by shadcn — APPROVED** [review]
Thank you.

**Pull request merged**
