### PR TITLE
fix(cli): change the default path for tailwind globals css

### PR DESCRIPTION
**Pull request by lem0n4id**
Fixes shadcn-ui/ui#1821 
Fixes shadcn-ui/ui#2302

TODO:
- [x] change default path for tailwind globals css file
- [ ] update in all the docs ([cli docs](https://github.com/shadcn-ui/ui/blob/main/apps/www/content/docs/cli.mdx), [astro docs](https://github.com/shadcn-ui/ui/blob/main/apps/www/content/docs/installation/astro.mdx), [gatsby docs](https://github.com/shadcn-ui/ui/blob/main/apps/www/content/docs/installation/gatsby.mdx), [laravel docs](https://github.com/shadcn-ui/ui/blob/main/apps/www/content/docs/installation/laravel.mdx), [next docs](https://github.com/shadcn-ui/ui/blob/main/apps/www/content/docs/installation/next.mdx), [remix docs](https://github.com/shadcn-ui/ui/blob/main/apps/www/content/docs/installation/remix.mdx), [vite docs](https://github.com/shadcn-ui/ui/blob/main/apps/www/content/docs/installation/vite.mdx))

### CODE REVIEW

**Comment by lem0n4id** [comment]
Should i update the docs as well?

For example, in [line 32 of nextjs docs](https://github.com/shadcn-ui/ui/blob/main/apps/www/content/docs/installation/next.mdx#L32) :
```diff
- Where is your global CSS file? › › app/globals.css
+ Where is your global CSS file? › › src/app/globals.css
```

**Comment by shadcn** [comment]
@lem0n4id The thing is not all apps uses the src dir. I think a better fix would be to detect the `src` dir and add it to the suggested path. What do you think?

**Comment by lem0n4id** [comment]
@shadcn That makes perfect sense.

So would this work as the fix?

```diff
- export const DEFAULT_TAILWIND_CSS = "app/globals.css"
+ export const DEFAULT_TAILWIND_CSS =       existsSync(path.resolve("./src"))? "src/app/globals.css" : "app/globals.css"
```

**Comment by shadcn** [comment]
@lem0n4id We'll need to do this per framework-basis. Check out the example for Next.js here: https://github.com/shadcn-ui/ui/blob/main/packages/cli/src/utils/get-project-info.ts

(I'm going to close this for now since we need a different implementation but feel free to reopen if you have any questions. Thank you.)

**Pull request closed without merging**
