### PR TITLE
fix(docs): present useForm when copy form

### LINKED ISSUE #1482: `import { useForm } from "react-hook-form"` not present in Form Guide
For someone who's absolutely copying and pasting form the guide, this would give an error, as `useForm` is not imported in the guide. 

Can simple fix it by adding that in the documentation.

### PR DESCRIPTION
**Pull request by onurhan1337**
When I tried it after the attached issue, I realized;
For someone who's absolutely copying and pasting form the guide, this would give an error, as useForm is not imported in the guide. So I fixed that.

Related issue: https://github.com/shadcn-ui/ui/issues/1482

Fix #1482

### CODE REVIEW

**Comment by onurhan1337** [comment]
@SoyDiego hi, any updates here?

**Review by SoyDiego — APPROVED** [review]

**Comment by SoyDiego** [comment]
> @SoyDiego hi, any updates here?

Hi @onurhan1337 I'm not part of this project only a contributor that sometimes review code but I cannot merge or do anything.
It's difficult here, the projects need more maintainers

**Comment by onurhan1337** [comment]
@SoyDiego Yes I understand you. Please don't get me wrong for tagging, it's just that since this is my first contribution to this project I'm not sure if I'm doing everything right and I wanted to ask you. Thanks for review

**Comment by SoyDiego** [comment]
> @SoyDiego Yes I understand you. Please don't get me wrong for tagging, it's just that since this is my first contribution to this project I'm not sure if I'm doing everything right and I wanted to ask you. Thanks for review

No problem. Looks good for me.
You can edit in your first message and write `Fix #1482`. Doing this you will link the PR to the issue and when they approve it and merge it, will close the issue automatically.
You have more info here https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by shadcn — APPROVED** [review]
Awesome. Thank you.

**Pull request merged**
