### PR TITLE
fix: toast add missing text color class

### LINKED ISSUE #1121: bug: title/description of `toast` hardly visible in darkmode
## Description
When using the default values after running `npx shadcn-ui@latest init` and `npx shadcn-ui@latest add toast`, the title and description of a toast are barely visible in darkmode:
image
Only after manually adding `dark:text-slate-100` (in my case at least with the default values) to both `ToastTitle` and `ToastDescription` is it possible to read the toast:
image

## Expected behavior
The text should be visible in darkmode without any additional changes

I'd be happy to help with a PR!

### PR DESCRIPTION
**Pull request by 1danii**
Should fix #1121 when using dark mode without CSS variables

### CODE REVIEW

**Review by dan5py — CHANGES_REQUESTED** [review]
Hi @1danii, thanks for the PR. You forgot to build the registry. 
You need to run:
```bash
pnpm build:registry
```

**Comment by 1danii** [comment]
Thanks for the correction, but when I run the script it changes all the files in the registry. Am I doing something wrong? @dan5py 
image

**Comment by dan5py** [comment]
@1danii I assume you're on Windows, right? If that's the case, Windows uses CRLF for line endings and that results in differences when `JSON.stringify` is used.

@shadcn I think we should add `.replace(/\\r/g, "")` to the `JSON.stringify` here:

https://github.com/shadcn-ui/ui/blob/3c9f7ca0e20638bf75833ef920f9b23f5d97bc71/apps/www/scripts/build-registry.ts#L104-L108

**Comment by 1danii** [comment]
@dan5py Yes the issue was only on windows, switching os fixed it, thanks for the fix!

**Review by dan5py — APPROVED** [review]
Perfect! 👍

**Review by shadcn — APPROVED** [review]
Thank you.

**Pull request merged**
