### PR TITLE
fix(www): table overflow

### LINKED ISSUE #416: Unexpected behavior on table horizontal scrolling
Hi @shadcn! Many thanks for this repo, amazing work 👏

Just noticed a strange behavior on the table component. When the content of the table is larger than the screen, a white space the size of the overflow is created. I have tried several things to fix this but nothing that works properly so far.

https://github.com/shadcn/ui/assets/15351304/1e2d097a-866d-449a-ac80-164dc82f796f

### PR DESCRIPTION
**Pull request by PixeledCode**
Replacement of #428 as there is a change in the directory structure

closes #416

### CODE REVIEW

**Comment by PixeledCode** [comment]
@shadcn @its-monotype does this PR look okay?

**Review by its-monotype — APPROVED** [review]

**Comment by its-monotype** [comment]
LGTM. Wow, I thought it was added a long time ago, strange that it's not merged yet

**Comment by PixeledCode** [comment]
@its-monotype workflow is still blocked even though they are approved?

**Comment by its-monotype** [comment]
> @its-monotype workflow is still blocked even though changes are approved?

It's awaiting approval from @shadcn

**Review by lucasfelixc — APPROVED** [review]

**Comment by lucasfelixc** [comment]
@shadcn Maybe this is a good PR to prioritize because this issue is affecting your site's user experience

https://github.com/shadcn-ui/ui/assets/64923932/2bc3a541-9281-4105-8ab5-4fef4d12046a

**Pull request merged**
