### PR TITLE
chore(apps): Update lodash

### LINKED ISSUE #3978: [bug]: There is a vulnerability in shadcn-ui@0.8.0 > lodash.template@4.5.0
### Describe the bug

When running `pnpm audit`  Ican see that there is a vulnerabilty in lodash and lodash is used by shadcn-ui under the hood.
high                             │ Command Injection in lodash  
│ Package                    │ lodash.template
│ Vulnerable versions │ <=4.5.0
│ Patched versions     │ <0.0.0
│ Paths                        │ . > shadcn-ui@0.8.0 > lodash.template@4.5.0
│ More info                 │ https://github.com/advisories/GHSA-35jh-r3h4-6jhm

### Affected component/components

shadcn-ui

### How to reproduce

Install "shadcn-ui": "^0.8.0" using pnpm

### Codesandbox/StackBlitz link

_No response_

### Logs

_No response_

### System Info

```bash
"shadcn-ui": "^0.8.0",
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

### PR DESCRIPTION
**Pull request by JensAstrup**
## Background
There is currently [a vulnerability in `lodash.template` that is of high severity](https://github.com/advisories/GHSA-35jh-r3h4-6jhm) which this repository relies on. No update has been made on their end and the project was last updated 5 years ago. 

## Solution
In order to resolve the vulnerability I replaced `lodash.template` with the current version of `lodash` and replaced usages of `import template from "lodash.template"` with `import { template } from "lodash"` which should achieve the same functionality

Closes #3978

### CODE REVIEW

**Comment by alexsilvar** [comment]
Any idea about what is missing to merge it?

**Comment by JensAstrup** [comment]
I have no idea who I'm waiting on or what the next step is, unless I'm missing something from `CONTRIBUTING.md`, I'm fairly certain I've done everything. @shadcn Any assistance here? 🥺

**Comment by MoSheikh** [comment]
Would also appreciate it if maintainers could take a look. Thank you!

**Comment by jaxazam** [comment]
Thanks for the work @JensAstrup.ave you heard back from them through any other channels? I'm guessing not...

**Comment by JensAstrup** [comment]
No, haven't heard anything yet :/

**Comment by alexsilvar** [comment]
Please expedite this PR

**Review by shadcn — APPROVED** [review]
Thank you.

> No update has been made on their end and the project was last updated 5 years ago.

I was surprised to read this but it's true.

**Comment by JensAstrup** [comment]
@shadcn Way more checks were run after that merge, I assume that has to do with the failing Vercel build? I'll take a look into the others 👀

**Comment by BowTiedFirefox** [comment]
is there an update or we can jump in to help?

**Comment by BowTiedLaplace** [comment]
Please fix this asap.

**Comment by gdragotto** [comment]
@shadcn can we help? It should be a simple fix in the CI

**Comment by dandubya** [comment]
Same urgency here. Thank you.

**Pull request merged**
