### PR TITLE
fix: quick fix to data attribute at CommandPrimitive.Item that was applying a disabled state style all the time

### PR DESCRIPTION
**Pull request by ricardoraposo**
Data attributes at <CommandPrimite.List /> component should be written as data-[disabled=true] in order to avoid styles being applied to element, even when it's not disabled.

### CODE REVIEW

**Comment by loiclefloch** [comment]
Hello @ricardoraposo, I had the same problem and fixed it the same way. Thank you for your Pull Request, it allowed me to be sure that my fix was correct.

**Comment by Sisableng** [comment]
@shadcn u need to review this PR

**Comment by AmsBarros** [comment]
Thank you so much. I was struggling with this too until I saw your PR

**Comment by pbroom** [comment]
+1 for this PR. I had the same issue and this change fixed it.

**Comment by imxfrq** [comment]
@ricardoraposo thankkkssss .. ui -> command.tsx -> [search] CommandPrimitive.Item -> [Copy Paste] 
ClassName={cn(
      "relative flex cursor-pointer select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none aria-selected:bg-accent aria-selected:text-accent-foreground data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-50 0"

**Comment by GabrielRuivo** [comment]
thanks so much @ricardoraposo, @shadcn please review this PR

**Review by shadcn — APPROVED** [review]
Thank you.

**Comment by kevinmitch14** [comment]
@shadcn there is still some missing pieces to `Command`, #2626 which is a follow up to #1980. ie. Incorrect usage of aria attributes instead of data atrributes.

**Pull request merged**
