### PR TITLE
feat: add motion-safe to animated components

### LINKED ISSUE #1029: Add motion-safe animations to entering components
First of all, great component library!

I think it's great that the components have been built with a11y in mind. The only I'm missing is the option for **reduced animations** since some users might prefer this setting.

A possible idea to achieve this would be adding the `motion-safe` class to certain components like `Dialog` or `Toast`.

### PR DESCRIPTION
**Pull request by DerTimonius**
## Description

This PR will add the `motion-safe` flag to components whose presence is animated in some way.

## Why

Some users, especially those with vestibular disorders or motion sensitivity, may experience discomfort, dizziness or other adverse reaction when exposed to motion animations. To relieve the developers, who use this package, of the burden of thinking about this fact, this PR aims to add the flag wherever necessary.

## How

Animations in tailwind [can be set `motion-safe` ](https://tailwindcss.com/docs/animation#prefers-reduced-motion) by adding a flag as a variant. This then picks up the user settings if they prefer reduced motion and applies the flag accordingly.

`motion-safe` has been added to the following components:
- `Alert Dialog`
- `Context Menu`
- `Dialog`
- `Dropdown Menu`
- `Hover Card`
- `Menubar`
- `Navigation Menu`
- `Popover`
- `Select`
- `Sheet`
- `Toast`
- `Tooltip`

Closes #1029

### CODE REVIEW

**Comment by shadcn** [comment]
Thank you. Reviewing...

**Comment by DerTimonius** [comment]
Hey @shadcn just wanted to check in and ask if there is something you need from me or if anything is unclear?

**Comment by DerTimonius** [comment]
any progress with the review?

**Comment by DerTimonius** [comment]
closing this as it's not wanted apparently

**Pull request closed without merging**
