### PR TITLE
fix(carousel): adjust types for embla-carousel-react@8

### LINKED ISSUE #2322: Type error: '"embla-carousel-react"' has no exported member named 'EmblaCarouselType'. Did you mean 'UseEmblaCarouselType'?
Error while Building NextJS Project
```
Type error: '"embla-carousel-react"' has no exported member named 'EmblaCarouselType'. Did you mean 'UseEmblaCarouselType'?

  1 | import * as React from "react"
  2 | import useEmblaCarousel, {
> 3 |   type EmblaCarouselType as CarouselApi,
    |        ^
  4 |   type EmblaOptionsType as CarouselOptions,
  5 |   type EmblaPluginType as CarouselPlugin,
  6 | } from "embla-carousel-react"
   Linting and checking validity of types  .```

### PR DESCRIPTION
**Pull request by Gomah**
Fixes #2322 , #2281 

Thanks to @akynau & @nianiam

### CODE REVIEW

**Comment by 0xtito** [comment]
Thanks @Gomah, @akynau , and @nianiam. Just updated `carousel.tsx` locally and this worked perfectly for me 👍

**Comment by 0xtito** [comment]
> Thanks @Gomah, @akynau , and @nianiam. Just updated `carousel.tsx` locally and this worked perfectly for me 👍

May have spoke too soon! When attempting to integrate it into a Zustand store (or even in just a component), I get `Unsafe assignment of an any value` for any variable that referred to the `CarouselApi` type.

For example, when just doing

`const [api, setApi] = React.useState<CarouselApi>()`

`api` would throw the eslint error `Unsafe assignment of an any value.`

What fixed it was adding `embla-carousel` as a dev dependency. For pnpm users, they suggest doing so [here](https://www.embla-carousel.com/api/options/)

image

**Comment by manangulati9** [comment]
> Fixes #2322 , #2281
> 
> Thanks to @akynau & @nianiam

Hi so I tried both of the above fixes but it breaks the type for plugins in useEmblaCarousel hook call.

`const [carouselRef, api] = useEmblaCarousel(
      {
        ...opts,
        axis: orientation === "horizontal" ? "x" : "y",
      },
      plugins //Type error with plugins)`

Error - 
` Argument of type '(CreatePluginType<LoosePluginType, {}>[] | undefined)[] | undefined' is not assignable to parameter of type 'CreatePluginType<LoosePluginType, {}>[] | undefined'.
     Type '(CreatePluginType<LoosePluginType, {}>[] | undefined)[]' is not assignable to type 'CreatePluginType<LoosePluginType, {}>[]'.
       Type 'CreatePluginType<LoosePluginType, {}>[] | undefined' is not assignable to type 'CreatePluginType<LoosePluginType, {}>'.
         Type 'undefined' is not assignable to type 'CreatePluginType<LoosePluginType, {}>'.
           Type 'undefined' is not assignable to type 'LoosePluginType'.`

**Review by shadcn — APPROVED** [review]
Thank you.

**Pull request merged**
