### PR TITLE
feat: added classname for indicator of progress

### PR DESCRIPTION
**Pull request by berat**
Hello, I don't know how to contribute to the Repository and I couldn't find any documentation.

This is my first time using this pack and I really like it. I fixed the part I found missing in my local. I didn't see anyone making such a request on Issue, but I still wanted to share. I just added the source code for now. If you want an example from the document, I can handle it.

What I do is; In the progress bar, the indicator initially comes as `bg-primary`. This is not something I want. I wanted to change the color of the indicator or something. That's why I defined a props for the indicator. We assign color as we want with indicatorClassName.

### CODE REVIEW

**Review by dan5py — APPROVED** [review]

**Comment by berat** [comment]
@shadcn

**Comment by theDanielJLewis** [comment]
I'm looking for this exact thing!

**Comment by berat** [comment]
We still waiting :) ...

**Comment by AyoCodess** [comment]
when will this get reviewed

**Pull request closed without merging**
