### PR TITLE
feat - Added a callback function support in Sidebar

### PR DESCRIPTION
**Pull request by rsvijaytiwari**
Added a `callback` function support in Sidebar which return internal state update of the Sidebar open `state` and `openMobile` state.

Usages Example: 
```
const [sideBarOpen, setSideBarOpen] = useState(true); // Use anywhere in component.
    return (
        <SidebarProvider callback={function (open, openMobile) {
            if (!open) {
                setTimeout(function () {
                    setSideBarOpen(open);
                }, 200);
            } else {
                setSideBarOpen(open)
            }
        }}>
  <SidebarProvider/>
```

### CODE REVIEW

**Comment by shadcn** [comment]
Can you share an example where this would be useful please? thank you.

**Comment by rsvijaytiwari** [comment]
Look, I want to use the default SideBar provided by Shadcn. Its default functionality is great, but when I customize it using state, the functionality stops working because it relies on external state rather than internal state. To solve this, I added a callback method that exposes the internal state (such as `state` and `openMobile`) of the SidebarProvider component to the outside. This way, I can add additional functionality based on the sidebar state. For example, I want to display a different logo for my company—a short version when the sidebar is closed, and a full-size logo when the sidebar is open.

```
export function SideBarNavigation({ content }: { content: any }) {
  const [sideBarOpen, setSideBarOpen] = useState(true);
  return (
    <SidebarProvider
      callback={function (open, openMobile) {
        if (!open) {
          setTimeout(function () {
            setSideBarOpen(open);
          }, 200);
        } else {
          setSideBarOpen(open);
        }
      }}
    >
      <Sidebar collapsible="icon">
        <SidebarHeader>
          {(function () {
            if (sideBarOpen) {
              return (
                <Link href={"/"}>
                  <Image
                    alt="InciLo Logo"
                    width={200}
                    height={200}
                    style={{
                      marginLeft: "-45px",
                      color: "transparent",
                      marginTop: 2,
                      height: 44,
                    }}
                    src="/assets/logos/logo-black.svg"
                  />
                </Link>
              );
            } else {
              return (
                <Link href={"/"}>
                  <Image
                    alt={"InciLo Logo"}
                    src={"/assets/logos/incilo-in-logo.png"}
                    height={200}
                    width={200}
                  />
                </Link>
              );
            }
          })()}
        </SidebarHeader>
        <SidebarContent>
          <SidebarGroup>
            <SidebarGroupLabel>Platform</SidebarGroupLabel>
            <SidebarMenu>
              {data.navMain.map(function (item, index) {
                if (item.items.length === 0) {
                  return (
                    <SidebarMenuButton asChild key={index}>
                      <Link href={item.url}>
                        <item.icon />
                        <span>{item.title}</span>
                      </Link>
                    </SidebarMenuButton>
                  );
                } else {
                  return (
                    <Collapsible
                      key={item.title}
                      asChild
                      defaultOpen={item.isActive}
                      className="group/collapsible"
                    >
                      <SidebarMenuItem>
                        <CollapsibleTrigger asChild>
                          <SidebarMenuButton tooltip={item.title}>
                            {item.icon && <item.icon />}
                            <span>{item.title}</span>
                            <ChevronRight className="ml-auto transition-transform duration-200 group-data-[state=open]/collapsible:rotate-90" />
                          </SidebarMenuButton>
                        </CollapsibleTrigger>
                        <CollapsibleContent>
                          <SidebarMenuSub>
                            {item.items?.map((subItem) => (
                              <SidebarMenuSubItem key={subItem.title}>
                                <SidebarMenuSubButton asChild>
                                  <a href={subItem.url}>
                                    <span>{subItem.title}</span>
                                  </a>
                                </SidebarMenuSubButton>
                              </SidebarMenuSubItem>
                            ))}
                          </SidebarMenuSub>
                        </CollapsibleContent>
                      </SidebarMenuItem>
                    </Collapsible>
                  );
                }
              })}
            </SidebarMenu>
          </SidebarGroup>
          <SidebarGroup className="group-data-[collapsible=icon]:hidden">
            <SidebarGroupLabel>Projects</SidebarGroupLabel>
            <SidebarMenu>
              {data.projects.map((item) => (
                <SidebarMenuItem key={item.name}>
                  <SidebarMenuButton asChild>
                    <a href={item.url}>
                      <item.icon />
                      <span>{item.name}</span>
                    </a>
                  </SidebarMenuButton>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <SidebarMenuAction showOnHover>
                        <MoreHorizontal />
                        <span className="sr-only">More</span>
                      </SidebarMenuAction>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent
                      className="w-48 rounded-lg"
                      side="bottom"
                      align="end"
                    >
                      <DropdownMenuItem>
                        <Folder className="text-muted-foreground" />
                        <span>View Project</span>
                      </DropdownMenuItem>
                      <DropdownMenuItem>
                        <Forward className="text-muted-foreground" />
                        <span>Share Project</span>
                      </DropdownMenuItem>
                      <DropdownMenuSeparator />
                      <DropdownMenuItem>
                        <Trash2 className="text-muted-foreground" />
                        <span>Delete Project</span>
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </SidebarMenuItem>
              ))}
              <SidebarMenuItem>
                <SidebarMenuButton className="text-sidebar-foreground/70">
                  <MoreHorizontal className="text-sidebar-foreground/70" />
                  <span>More</span>
                </SidebarMenuButton>
              </SidebarMenuItem>
            </SidebarMenu>
          </SidebarGroup>
        </SidebarContent>
        <SidebarFooter>
          <SidebarMenu>
            <SidebarMenuItem>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <SidebarMenuButton
                    size="lg"
                    className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
                  >
                    <Avatar className="h-8 w-8 rounded-lg">
                      <AvatarImage
                        src={data.user.avatar}
                        alt={data.user.name}
                      />
                      <AvatarFallback className="rounded-lg">CN</AvatarFallback>
                    </Avatar>
                    <div className="grid flex-1 text-left text-sm leading-tight">
                      <span className="truncate font-semibold">
                        {data.user.name}
                      </span>
                      <span className="truncate text-xs">
                        {data.user.email}
                      </span>
                    </div>
                    <ChevronsUpDown className="ml-auto size-4" />
                  </SidebarMenuButton>
                </DropdownMenuTrigger>
                <DropdownMenuContent
                  className="w-[--radix-dropdown-menu-trigger-width] min-w-56 rounded-lg"
                  side="bottom"
                  align="end"
                  sideOffset={4}
                >
                  <DropdownMenuLabel className="p-0 font-normal">
                    <div className="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
                      <Avatar className="h-8 w-8 rounded-lg">
                        <AvatarImage
                          src={data.user.avatar}
                          alt={data.user.name}
                        />
                        <AvatarFallback className="rounded-lg">
                          CN
                        </AvatarFallback>
                      </Avatar>
                      <div className="grid flex-1 text-left text-sm leading-tight">
                        <span className="truncate font-semibold">
                          {data.user.name}
                        </span>
                        <span className="truncate text-xs">
                          {data.user.email}
                        </span>
                      </div>
                    </div>
                  </DropdownMenuLabel>
                  <DropdownMenuSeparator />
                  <DropdownMenuGroup>
                    <DropdownMenuItem>
                      <Sparkles />
                      Upgrade to Pro
                    </DropdownMenuItem>
                  </DropdownMenuGroup>
                  <DropdownMenuSeparator />
                  <DropdownMenuGroup>
                    <DropdownMenuItem>
                      <BadgeCheck />
                      Account
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <CreditCard />
                      Billing
                    </DropdownMenuItem>
                    <DropdownMenuItem>
                      <Bell />
                      Notifications
                    </DropdownMenuItem>
                  </DropdownMenuGroup>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem>
                    <LogOut />
                    Log out
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </SidebarMenuItem>
          </SidebarMenu>
        </SidebarFooter>
        <SidebarRail />
      </Sidebar>
      <SidebarInset>
        <header className="flex h-16 shrink-0 border-b items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12 sticky top-0 z-40 w-full bg-white">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1" />
            <Separator orientation="vertical" className="mr-2 h-4" />
            <Breadcrumb>
              <BreadcrumbList>
                <BreadcrumbItem className="hidden md:block">
                  <BreadcrumbLink href="#">
                    Building Your Application
                  </BreadcrumbLink>
                </BreadcrumbItem>
                <BreadcrumbSeparator className="hidden md:block" />
                <BreadcrumbItem>
                  <BreadcrumbPage>Data Fetching</BreadcrumbPage>
                </BreadcrumbItem>
              </BreadcrumbList>
            </Breadcrumb>
          </div>
        </header>
        <div className={"content-area"}>{content}</div>
      </SidebarInset>
    </SidebarProvider>
  );
}

```

**Comment by shadcn** [comment]
@rsvijaytiwari You should be able to access the state using the `useSidebar` hook. See https://ui.shadcn.com/docs/components/sidebar#usesidebar

**Comment by rsvijaytiwari** [comment]
Buddy, I tried `useSidebar` but I don't found the proper implmentation docs for it. Could you please provide me the example how can I implment `useSidebar` in my future project.

**Comment by shadcn** [comment]
Here's an example using `useSidebar` to show a 👋 when the sidebar is collapsed. See `app-sidebar.tsx`: https://codesandbox.io/p/devbox/glyn83?file=%2Fcomponents%2Fapp-sidebar.tsx%3A161%2C1-162%2C1

**Pull request closed without merging**
