### PR TITLE
feat: Enhanced Tailwind support inside CVA and cn

### PR DESCRIPTION
**Pull request by ap-1**
[This snippet](https://cva.style/docs/installation#intellisense) inside of `settings.json` allows the Tailwind CSS extension to provide intellisense for the strings inside CVA. It has no effect if the Tailwind CSS extension is not installed, but I believe many of `shadcn/ui`'s users already do. The same has been done for the `cn()` helper.

I also added a few more changes:

- The Tailwind CSS extension is now in the "recommendations" field in `.vscode/extensions.json`.
- There are now instructions to install the Tailwind CSS extension inside a new "Editor setup" docs page.
- `cva` is now in the list of callees in the `eslint-plugin-tailwindcss` settings.

### CODE REVIEW

**Comment by its-monotype** [comment]
https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/classnames-order.md#callees-default-classnames-clsx-ctl-cva-tv

**Comment by its-monotype** [comment]
And do not use "prettier-plugin-tailwindcss"  and "eslint-plugin-tailwindcss" simultaneously, it can cause unreal lags in VSCode

**Comment by ap-1** [comment]
Depending on how #528 is implemented, we might require a couple changes here

**Comment by ap-1** [comment]
Relevant: https://github.com/joe-bell/cva/discussions/85#discussioncomment-5014769

**Pull request closed without merging**
