### PR TITLE
feat(components): add "use client" directive to carousel, resizable components

### PR DESCRIPTION
**Pull request by grayashh**
carousel, resizable components to be used by the app router, a "use client" directive is required.

### CODE REVIEW

**Review by SoyDiego — APPROVED** [review]

**Comment by shadcn** [comment]
@grayashh did you mean to close this?

**Comment by grayashh** [comment]
@shadcn I didn't intend to close this PR.
However, it seems that it was accidentally closed when I registered another PR on the same branch to fix another error. 
Can I register the PR again?

**Comment by shadcn** [comment]
Yes please. This still needed. Happy to merge a new PR.

**Comment by grayashh** [comment]
@shadcn https://github.com/shadcn-ui/ui/pull/2319
Thank you, I have reopened the new PR

**Pull request closed without merging**
