### PR TITLE
bug fix: type error in chart.tsx

### LINKED ISSUE #4229: [bug]: Chart component does not compile
### Describe the bug

when building in nextjs 14.1.3 with typescript 5.x, the chart component throws an error:
   Linting and checking validity of types  ..Failed to compile.
```
./src/components/ui/chart.tsx:82:9
Type error: Type 'string[]' is not assignable to type 'string | TrustedHTML'.

  80 |     <style
  81 |       dangerouslySetInnerHTML={{
> 82 |         __html: Object.entries(THEMES).map(
     |         ^
  83 |           ([theme, prefix]) => `
  84 | ${prefix} [data-chart=${id}] {
  85 | ${colorConfig
```
### Affected component/components

Chart

### How to reproduce

Run `next lint`. It breaks the build.

The fix could be as simple as refactoring the component to be:
```diff
const ChartStyle = ({ id, config }: { id: string; config: ChartConfig }) => {
  const colorConfig = Object.entries(config).filter(
    ([_, config]) => config.theme || config.color,
  );

  if (!colorConfig.length) {
    return null;
  }

  return (
    <style
      dangerouslySetInnerHTML={{
        __html: Object.entries(THEMES).map(
          ([theme, prefix]) => `
${prefix} [data-chart=${id}] {
${colorConfig
  .map(([key, itemConfig]) => {
    const color =
      itemConfig.theme?.[theme as keyof typeof itemConfig.theme] ||
      itemConfig.color;
    return color ? `  --color-${key}: ${color};` : null;
  })
  .join("\n")}
}
`,
-         ),
+         ).join("\n"),
      }}
    />
  );
};
```

### Codesandbox/StackBlitz link

_No response_

### Logs

```bash
bun run build
$ next build
   ▲ Next.js 14.1.3
   - Environments: .env
   - Experiments (use at your own risk):
     · instrumentationHook

   Creating an optimized production build ...
(node:55040) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 ⚠ Compiled with warnings

./node_modules/@opentelemetry/instrumentation-winston/build/src/instrumentation.js
Module not found: Can't resolve '@opentelemetry/winston-transport' in '/Users/arielfogel/Development/pillar_apps/cloud_dashboard/node_modules/@opentelemetry/instrumentation-winston/build/src'

Import trace for requested module:
./node_modules/@opentelemetry/instrumentation-winston/build/src/instrumentation.js
./node_modules/@opentelemetry/instrumentation-winston/build/src/index.js
./node_modules/@opentelemetry/auto-instrumentations-node/build/src/utils.js
./node_modules/@opentelemetry/auto-instrumentations-node/build/src/index.js
./src/instrumentation.node.ts
./src/app/api/v1/messages/route.ts

./node_modules/@descope/node-sdk/dist/index.esm.js
A Node.js API is used (process.versions at line: 1) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

Import trace for requested module:
./node_modules/@descope/node-sdk/dist/index.esm.js
./node_modules/@descope/nextjs-sdk/dist/server/authMiddleware.js
./node_modules/@descope/nextjs-sdk/dist/server/index.js

   Linting and checking validity of types  ..Failed to compile.

./src/components/ui/chart.tsx:82:9
Type error: Type 'string[]' is not assignable to type 'string | TrustedHTML'.

  80 |     <style
  81 |       dangerouslySetInnerHTML={{
> 82 |         __html: Object.entries(THEMES).map(
     |         ^
  83 |           ([theme, prefix]) => `
  84 | ${prefix} [data-chart=${id}] {
  85 | ${colorConfig
   Linting and checking validity of types  ...error: script "build" exited with code 1
```

### System Info

```bash
OSX
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

### PR DESCRIPTION
**Pull request by afogel**
# Current Issue
when running `next lint`, the typescript compiler fails on the chart component (closes #4229 )
`Type error: Type 'string[]' is not assignable to type 'string | TrustedHTML'.`

# Resolution

We can coerce the `string[]` into a valid type by `join`ing.

### CODE REVIEW

**Comment by shadcn** [comment]
@afogel can you share your tsconfig.json please? I'll try and reproduce.

**Comment by afogel** [comment]
```
{
  "compilerOptions": {
    "target": "esnext",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "allowImportingTsExtensions": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"],
      "@/zodAutoGenSchemas": ["./prisma/zod/index"]
    },
    "baseUrl": "./"
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
```

**Comment by zayq** [comment]
Got the same error, fixed it like so for Chart Style : 

const ChartStyle = ({ id, config }: { id: string; config: ChartConfig }) => {
  const colorConfig = Object.entries(config).filter(
    ([_, config]) => config.theme ?? config.color
  );

  if (!colorConfig.length) {
    return null;
  }

  return (
    <style
      dangerouslySetInnerHTML={{
        __html: Object.entries(THEMES)
          .map(
            ([theme, prefix]) => `
            ${prefix} [data-chart=${id}] {
            ${colorConfig
              .map(([key, itemConfig]) => {
                const color =
                  itemConfig.theme?.[theme as keyof typeof itemConfig.theme] ??
                  itemConfig.color;
                return color ? `  --color-${key}: ${color};` : null;
              })
              .filter(Boolean)
              .join("\n")}
        }`).join(''),
      }}
    />
  )
}

**Comment by afogel** [comment]
> Got the same error, fixed it like so for Chart Style :
> 
> const ChartStyle = ({ id, config }: { id: string; config: ChartConfig }) => { const colorConfig = Object.entries(config).filter( ([_, config]) => config.theme ?? config.color );
> 
> if (!colorConfig.length) { return null; }
> 
> return ( <style dangerouslySetInnerHTML={{ __html: Object.entries(THEMES) .map( ([theme, prefix]) => `${prefix} [data-chart=${id}] { ${colorConfig .map(([key, itemConfig]) => { const color = itemConfig.theme?.[theme as keyof typeof itemConfig.theme] ?? itemConfig.color; return color ?` --color-${key}: ${color};` : null; }) .filter(Boolean) .join("\n")} }`).join(''), }} /> ) }

yeah, that's basically the same fix as is proposed in this PR.

**Comment by AliceReachIndustries** [comment]
Was having the same issue and the PRs proposed fix worked no issues 👍

**Review by P156HAM — APPROVED** [review]

**Comment by shadcn** [comment]
@afogel any chance you can run `pnpm build:registry` and push the files please?

**Review by BouakkazLotfiG — APPROVED** [review]

**Comment by BouakkazLotfiG** [comment]
the PR changes worked for me

**Comment by afogel** [comment]
@shadcn done. thanks for all your incredible work!!

**Review by shadcn — APPROVED** [review]

**Comment by henningsieh** [comment]
this is still broken, but why?? https://github.com/shadcn-ui/ui/issues/4229#issuecomment-3035146577

**Pull request merged**
