### PR TITLE
chore: upgrade `@radix-ui/react-select` to 2.0.0

### PR DESCRIPTION
**Pull request by harryzcy**

### CODE REVIEW

**Review by SoyDiego — APPROVED** [review]

**Comment by shadcn** [comment]
Do you know where I can find the release notes for this version? I can't find it here: https://www.radix-ui.com/primitives/docs/overview/releases

Thank you

**Comment by harryzcy** [comment]
It seems https://github.com/radix-ui/primitives/pull/2174 is why it's breaking.

_Originally posted by @benoitgrelard in https://github.com/radix-ui/primitives/pull/2174#discussion_r1210334603_
> Making this a major as this is potentially a breaking change for people who were relying on using an option with `value=""` instead of the `placeholder`.

**Comment by harryzcy** [comment]
@shadcn Hi, is there any update to this?

**Comment by shadcn** [comment]
@harryzcy Thanks for the links. Looks good.

**Review by shadcn — APPROVED** [review]

**Pull request merged**
