### PR TITLE
Update dark-mode/vite.mdx

### PR DESCRIPTION
**Pull request by sankaSanjeeva**
Updated vite.mdx file adding a new type called Theme. Now 'theme' has a type definition when we use the 'useTheme' hook

### CODE REVIEW

**Review by dan5py — APPROVED** [review]
👍

**Comment by shadcn** [comment]
@sankaSanjeeva Could you fix the code format check please?

```
www:format:check: [warn] content/docs/dark-mode/vite.mdx
www:format:check: [warn] Code style issues found in the above file. Forgot to run Prettier?
```

**Comment by sankaSanjeeva** [comment]
@shadcn done

**Review by shadcn — APPROVED** [review]
Thank you.

**Pull request merged**
