### PR TITLE
fix(docs): added missing `CommandList` to combobox docs

### PR DESCRIPTION
**Pull request by neighborhood999**
I think this PR can fixed: #3732, #3707, #809, #3012, #3637

### CODE REVIEW

**Comment by ezeparziale** [comment]
I think that this need `cmdk == 1.0.0`

https://github.com/pacocoursey/cmdk/releases/tag/v1.0.0

**Comment by mpourismaiel** [comment]
Please replace `data-[disabled]` classes with `aria-disabled` for `CommandPrimitive.Item` as well. Other changes may be required per `cmdk@v1` but that was the only issue I encountered.

**Comment by neighborhood999** [comment]
Hi @ezeparziale and @mpourismaiel,

Thanks for reminding me, I applied your guys' suggestions.

**Comment by braden-w** [comment]
Stumbled upon the same issue and fix independently today, was crashing local development. Good to see a fix and hope it gets merged soon 👍

**Review by ahmadawais — APPROVED** [review]
Just tested this. Looks good to me! ✔︎

**Comment by neighborhood999** [comment]
Hey @shadcn, can you help to verify this PR : )?

**Comment by luchillo17** [comment]
@neighborhood999 There's some conflicts and the checks are not passing, doubt it will be reviewed while that's the case.

**Comment by shadcn** [comment]
@neighborhood999 I believe this is fixed now. Going to close this as fixed. Feel free to reopen if not. Appreciate your help.

**Comment by nullnullsieben** [comment]
Google Chrome Version 127.0.6533.89 (Official Build) (64-bit)

shadcn ***@***.***> schrieb am Mo., 5. Aug. 2024, 12:23:

**Pull request closed without merging**
