### PR TITLE
fix(www/registry): fix select component content item on click will pass to below (#1220)

### LINKED ISSUE #1220: Select issue in mobile mode
Hi,
Select mode works well in desktop mode..but once you inspect it in mobile device is has a bug with background clock.

Here I have two screen shots. The select item overlay works fine on desktop mode but in mobile mode when you press an item the background button is also triggered as you can see on my screenshot.

it also triggers the background cancel button.

Screenshot 2023-08-13 at 18 12 11
Screenshot 2023-08-13 at 18 12 18

### PR DESCRIPTION
**Pull request by xmliszt**
I was able to find a workaround for this issue suggested in the **radix ui** community. Hence applied the workaround here to fix the issue in shadcn ui.

original issue: https://github.com/radix-ui/primitives/issues/1658 

this pr fix #1220

### CODE REVIEW

**Comment by JohnGemstone** [comment]
When choosing to prevent 'ontouchstart' it disables any scrolling behaviour, if you look in the comments someone recommended using 'ontouchend' instead which works with scrolling too 👌

**Comment by xmliszt** [comment]
> When choosing to prevent 'ontouchstart' it disables any scrolling behaviour, if you look in the comments someone recommended using 'ontouchend' instead which works with scrolling too 👌

I tried with `ontouchend` but the pass through still happens, I suspect the pass through effect is already received by the element below after `ontouchstart`. will investigate further for alternatives

**Comment by xmliszt** [comment]
> > When choosing to prevent 'ontouchstart' it disables any scrolling behaviour, if you look in the comments someone recommended using 'ontouchend' instead which works with scrolling too 👌
> 
> I tried with `ontouchend` but the pass through still happens, I suspect the pass through effect is already received by the element below after `ontouchstart`. But yeah thanks for pointing out the scroll behaviour will be gone with this `ontouchstart` implementation. Will investigate further for alternatives

Follow up to investigation. When I set `ontouchstart`, and I purposely put the `ontouchstart` as well as `onClickCaptured` event listener on the below clickable element (which is a <Card> in my case), the weird thing happens:

- the below element only receive `onClickCaptured` event but not `ontouchstart` event
- for the <SelectContent>, I print out `touchEvent.targetTouches` and only receives 1 target which is the <SelectItem>

So my hypothesis is:

somehow the one finger touch once is registered as both **click** and **touch**, then they both trigger different listeners independently.

**Comment by xmliszt** [comment]
The root cause of this issue will be fixed in radix-ui. I have submitted a PR for their review: https://github.com/radix-ui/primitives/pull/2403

**Pull request closed without merging**
