### PR TITLE
fix: tailwind config updater parser

### PR DESCRIPTION
**Pull request by matsuyoshi30**
Fixed ArrayLiteralExpression being parsed as text in tailwindcss config file.

For example, when the following input is received

```javascript
const config: Config = {
  ...
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "ui-sans-serif",
          "sans-serif",
        ],
      },
    }
    ...
  }
  ...
}
```

before

```javascript
const config: Config = {
  ...
  theme: {
    extend: {
      fontFamily: {
        sans: [\n          "ui-sans-serif",\n          "sans-serif",\n        ]
      },
    }
    ...
  }
  ...
}
```

after

```javascript
const config: Config = {
  ...
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'ui-sans-serif',
          'sans-serif'
        ]
      },
    }
    ...
  }
  ...
}
```

### CODE REVIEW

**Review by shadcn — APPROVED** [review]
Ah thank you.

**Comment by matsuyoshi30** [comment]
Some tests are failed, so I'm going to commit additional fixes.

**Comment by matsuyoshi30** [comment]
If there is a spread element in the array, it seems tricky to unquote it so that it is not treated as a string.

I'll think more about it, but if anyone has a better idea, I'd like to hear it!

**Comment by bcorbold** [comment]
@matsuyoshi30 I've been looking into this area for an issue I've seen with `[string, object]` tuples in `fontSize` that I think can build off the work you've started here. I'm still looking through some test cases now, but I can see if the approach I've started might also solve the spread elements you mentioned 👀

**Comment by bcorbold** [comment]
Just put up a PR branched off of this to ensure @matsuyoshi30 gets the credit for starting this! That _should_ fix the spread issues mentioned in nested objects/arrays

#5711

**Comment by matsuyoshi30** [comment]
Thank you @bcorbold! I'll close this PR.

**Pull request closed without merging**
