### PR TITLE
update `<command />` to open only dialog when `cmd+k` is pressed.

### PR DESCRIPTION
**Pull request by vinaykulk621**
Before 

https://github.com/shadcn-ui/ui/assets/94120295/6a705279-c501-44d6-9ffd-b183d3451a8e

After

https://github.com/shadcn-ui/ui/assets/94120295/9f4da345-ed52-4404-a063-78521cbd7e93

### CODE REVIEW

**Comment by shadcn** [comment]
@vinaykulk621 Does this add support for `ctrl+k`? Is this the default for Windows?

**Comment by vinaykulk621** [comment]
@shadcn Yes, As you can see in both videos, i am pressing `ctrl+k`.
The updated code do not open chrome's search bar.

here is the chrome's shortcuts for windows [https://support.google.com/chrome/answer/157179](https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ctab-window-shortcuts%2Cgoogle-chrome-feature-shortcuts%2Cwebpage-shortcuts%2Cmouse-shortcuts%2Caddress-bar-shortcuts)



image

**Comment by shadcn** [comment]
Can you visit the [preview env](https://ui-git-fork-vinaykulk621-command-shadcn-pro.vercel.app) and see if it now works as expected?

**Comment by vinaykulk621** [comment]
@shadcn  works Perfectly

https://github.com/shadcn-ui/ui/assets/94120295/253804ed-b7fb-4163-b282-b87e4ab761b2

**Review by shadcn — APPROVED** [review]
Let's merge! Thank you.

**Pull request merged**
