### PR TITLE
Debugged:   Import path correction for `Next.JS` (apps/www/content/docs/installation/next.mdx)

### PR DESCRIPTION
**Pull request by GrungeElFz**
> Docs > [Next.js](https://ui.shadcn.com/docs/installation/next)
> 
> **Next.js**
> Install and configure Next.js
>
> (5) That's it
>
> You can now start adding components to your project.
>
> ```
> npx shadcn-ui@latest add button
> ```
>
> The command above will add the Button component to your project. You can then import it like this:
>
> ```
> import { Button } from "@/components/ui"
>  
> export default function Home() {
>  return (
>    <div>
>      <Button>Click me</Button>
>   </div>
>  )
> }
> ```
>
___

Ticket:  [#838](https://github.com/shadcn/ui/issues/838)

`import { Button } from "@/components/ui"` will result with: 
```
⚠ Error (TS2307) | Cannot find module or its corresponding type declarations.
```
___

Correction: `import { Button } from "@/components/ui/button"`

### CODE REVIEW

**Review by dan5py — CHANGES_REQUESTED** [review]
Hi @GrungeElFz, thank you so much. Now that I look closely, also the other framework's imports are incorrect (apart from `Astro`). Could you please update them too?

**Comment by GrungeElFz** [comment]
Hi, @dan5py 👋

I'd be happy to update the import paths from other frameworks as well 😊👍

**Comment by GrungeElFz** [comment]
@dan5py 

Path corrections:

✅ `Next.JS`
✅ `Gatsby`
✅ `Remix`
✅ `Vite`

**Review by dan5py — APPROVED** [review]
Awesome. Thank you.

**Comment by GrungeElFz** [comment]
⇡ Reminder: This pull request has not been merged. [@dan5py]

**Comment by jason-hwang** [comment]
Let's merge asap 🛠️ 
I spent a lot of time on the correction. 

@GrungeElFz Nice PR!

**Comment by GrungeElFz** [comment]
⇡ Reminder: This pull request has not been merged. [@dan5py]

**Review by shadcn — APPROVED** [review]
Somehow this doc typo resulted in several issues and 6 DMs :)

Thanks for the fix!

**Pull request merged**
